name: workflow
on:
  workflow_dispatch:
  push:

jobs:
  next-app:
    uses: ./.github/workflows/next-app.yaml
    secrets: inherit
    permissions:
      actions: read
      contents: read
      packages: write
      id-token: write
      security-events: write
    with:
      app: spillerom-kafkaviewer
      base-path: /
